# Blood Bank Management System - Complete SQL Schema

-- ============================================
-- 1. BLOOD BANKS TABLE
-- ============================================
create table if not exists public.blood_banks (
  id bigint generated by default as identity primary key,
  name text not null,
  city text not null,
  address text not null,
  phone text not null,
  lat double precision not null,
  lng double precision not null,
  inventory jsonb not null default '{}'::jsonb,
  created_at timestamptz default now()
);

-- ============================================
-- 2. REQUESTS TABLE (Hospital Blood Requests)
-- ============================================
create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  patient_name text not null,
  hospital_name text not null,
  blood_type text not null,
  units integer not null check (units > 0),
  city text not null,
  contact_number text not null,
  status text not null default 'pending',
  notes text,
  created_at timestamptz not null default now()
);

-- ============================================
-- 3. DONATIONS TABLE (Blood Donations)
-- ============================================
create table if not exists public.donations (
  id bigint generated by default as identity primary key,
  donor_name text not null,
  blood_type text not null,
  units integer not null check (units > 0),
  city text not null,
  contact_number text not null,
  availability_date date,
  status text not null default 'pending',
  notes text,
  created_at timestamptz not null default now()
);

-- ============================================
-- 4. DONORS TABLE (NEW - Self-Registration)
-- ============================================
create table if not exists public.donors (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique not null,
  phone text not null,
  blood_type text not null,
  age integer,
  city text not null,
  address text,
  lat double precision not null,
  lng double precision not null,
  last_donation_date date,
  status text not null default 'pending',
  approval_date timestamptz,
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================
-- 5. ADMIN USERS TABLE (NEW - Admin Panel)
-- ============================================
create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null,
  email text unique not null,
  full_name text,
  role text not null default 'admin',
  is_active boolean default true,
  created_at timestamptz not null default now()
);

-- ============================================
-- 6. APPROVAL LOGS TABLE (NEW - Track Approvals)
-- ============================================
create table if not exists public.approval_logs (
  id bigint generated by default as identity primary key,
  donor_id bigint not null references public.donors(id) on delete cascade,
  admin_id bigint not null references public.admin_users(id) on delete cascade,
  action text not null,
  reason text,
  created_at timestamptz not null default now()
);

-- ============================================
-- INSERT DUMMY ADMIN USER
-- ============================================
INSERT INTO public.admin_users (username, password, email, full_name, role)
VALUES 
  ('admin', '<set-in-your-env>', 'admin@bloodbank.com', 'Admin User', 'admin'),
  ('superadmin', '<set-in-your-env>', 'superadmin@bloodbank.com', 'Super Admin', 'superadmin')
ON CONFLICT (username) DO NOTHING;

-- ============================================
-- INSERT SAMPLE BLOOD BANKS
-- ============================================
INSERT INTO public.blood_banks (name, city, address, phone, lat, lng, inventory)
VALUES
  ('CityCare Blood Center', 'Delhi', 'A-23, Connaught Place, New Delhi', '+91 9810011111', 28.6315, 77.2167,
   '{"A+":18,"A-":4,"B+":22,"B-":6,"AB+":10,"AB-":2,"O+":26,"O-":7}'::jsonb),
  ('LifeLine Blood Bank', 'Noida', 'Sector 18, Noida, Uttar Pradesh', '+91 9810022222', 28.5706, 77.326,
   '{"A+":12,"A-":3,"B+":16,"B-":3,"AB+":6,"AB-":1,"O+":20,"O-":5}'::jsonb),
  ('RedCross Blood Services', 'Gurgaon', 'DLF Cyber Hub, Gurgaon', '+91 9810033333', 28.4595, 77.1006,
   '{"A+":25,"A-":5,"B+":30,"B-":8,"AB+":12,"AB-":3,"O+":35,"O-":9}'::jsonb)
ON CONFLICT DO NOTHING;

-- ============================================
-- USEFUL QUERIES
-- ============================================

-- View all blood banks
-- SELECT * FROM blood_banks;

-- Find blood banks with specific blood type (A+ available)
-- SELECT * FROM blood_banks 
-- WHERE (inventory->>'A+')::int > 0;

-- Update inventory for a specific blood bank
-- UPDATE blood_banks 
-- SET inventory = jsonb_set(
--   inventory,
--   '{A+}',
--   '50'
-- )
-- WHERE id = 1;

-- Find nearby donors by blood type and location
-- SELECT id, name, email, phone, blood_type, city, lat, lng,
--   (6371 * acos(cos(radians(28.6315)) * cos(radians(lat)) * 
--   cos(radians(lng) - radians(77.2167)) + 
--   sin(radians(28.6315)) * sin(radians(lat)))) AS distance_km
-- FROM donors
-- WHERE blood_type = 'B+' AND status = 'approved'
-- ORDER BY distance_km ASC
-- LIMIT 10;

-- Count pending donor approvals
-- SELECT COUNT(*) as pending_approvals FROM donors WHERE status = 'pending';

-- Get all approved donors in a city
-- SELECT id, name, email, phone, blood_type, city, lat, lng, last_donation_date 
-- FROM donors 
-- WHERE city = 'Delhi' AND status = 'approved'
-- ORDER BY last_donation_date DESC;

-- Update donor status to approved
-- UPDATE donors SET status = 'approved', approval_date = NOW() WHERE id = 1;

-- Reject donor with reason
-- UPDATE donors SET status = 'rejected', rejection_reason = 'Health issues' WHERE id = 2;

-- Find low stock blood banks
-- SELECT name, city, inventory
-- FROM blood_banks
-- WHERE (inventory->>'A+')::int < 10
--   OR (inventory->>'B+')::int < 10
--   OR (inventory->>'O+')::int < 10
--   OR (inventory->>'AB+')::int < 10;
